# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 ninesix-ai studio
#
# cargo-deny covers exactly one layer: crate dependency licenses.
#
# The crate side is effectively dependency-free (Cargo.lock is just the serde_json
# tree), so the real model/component red lines - Qwen / SenseVoice / Kokoro /
# sherpa-onnx, plus the commercially banned NLLB-200 / SeamlessM4T / LibreTranslate -
# are not crates.io entries and are invisible here. Those are enforced by the
# `license_gate` unit tests, which run with `cargo test` in CI.
#
# Where each layer runs: this crate-layer check is executed by CI only; on a dev
# machine use `cargo test --release --lib license_gate` for the model/component layer.
#
# Keep this file to the field set that upstream's own deny.toml proves cargo-deny
# accepts (`allow`, `confidence-threshold`). An unknown key makes cargo-deny fail to
# deserialize the whole config, and a config that never loaded is not a gate: the
# previous revision carried `[licenses.bans]`, `copyleft` and `allow-osi-fsf-free`
# from a template and the licenses check had therefore never run.
#
# Anything not listed under `allow` fails the check (fail-closed), which mirrors
# ALLOWED_LICENSES in src/license_gate.rs. Banning a license by name is redundant
# here; the explicit blacklist lives in license_gate.rs (DENIED_LICENSES).

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSD-3-Clause",
    "CC0-1.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.93
